.MODEL SMALL
.STACK 100H
.DATA
FNAME DW 'NAME: RAIHAN AHMED', 0AH, 0DH, 24H
ID DW 'ID: 19-40978-2', 0AH, 0DH, 24H
BYEAR DW 'BIRTH YEAR: 1998', 0AH, 0DH, 24H
.CODE MAIN
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    LEA DX, FNAME
    MOV AH, 09H
    INT 21H
    
    LEA DX, ID
    MOV AH, 09H
    INT 21H
    
    LEA DX, BYEAR
    MOV AH, 09H
    INT 21H
    
    MOV AH, 00H
    INT 16H
    
    MAIN ENDP
END MAIN